{
 "title": "MMP-exporter example dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total rack power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(voltamps)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total rack power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum(voltamps)", "legendFormat": "Total rack power" }
   ]
  },
  {
   "title": "Cost per day (approx.)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(voltamps[1d])) * 24 / 1000 * 0.39",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "voltamps", "legendFormat": "{{instance}} {{name}}" }
   ]
  },
  {
   "title": "True RMS current",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "true_rms_current", "legendFormat": "{{instance}} {{name}}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "true_rms_voltage", "legendFormat": "{{instance}} {{name}}" }
   ]
  }
 ]
}